# This is a basic workflow to help you get started with Actions

name: build lambda

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    
env:
  ARTIFACT_NAME: serverless-1.0-SNAPSHOT.jar
  CODEDEPLOY_APPLICATION_NAME: csye6225-webapp-deployment
  CODEDEPLOY_APPLICATION_GROUP_NAME: csye6225-webapp-deployment-group
  
jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build with maven
        run: mvn -B package --file pom.xml

      - name: package
        run: mvn package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy File to S3
        run: |
          aws s3 cp target/serverless-1.0-SNAPSHOT.jar s3://csye6225-serverless-bucket
      - name: update lambda function
        run: |
          aws lambda update-function-code --function-name VerifyEmailFunction --s3-bucket csye6225-serverless-bucket --s3-key serverless-1.0-SNAPSHOT.jar
