# This is a basic workflow to help you get started with Actions

name: build lambda

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    
env:
  ARTIFACT_NAME: serverless.zip
  
jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build zip file
        run: |
          mkdir severless_artifact
          zip -r ${{ env.ARTIFACT_NAME }} emailVerification.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy File to S3
        run: |
          aws lambda update-function-code --function-name csye6225-email-verification --zip-file fileb://${{ env.ARTIFACT_NAME }}
